### ISSUE TITLE
Live Preview gets broken when the extension is enabled

### ISSUE THREAD

**Issue by AlokBhushanJss** [ErickShepherd/more-languages-for-adobe-brackets#1]
Hi 
I recently installed your extension into my brackets.

But when I tried to use live preview, it shows the following error

![capture](https://user-images.githubusercontent.com/36888646/42543150-26f3ef1e-84c8-11e8-98c0-efdcafac9317.JPG)
![capture1](https://user-images.githubusercontent.com/36888646/42543157-2d10ae5a-84c8-11e8-9da0-0a6f888a0341.JPG)

Notice that I have an open HTML file in my project folder as well as in working files.

Problem goes away if I reload brackets without extensions or disable your extension.
I am on Windows OS 10 version 1803 build 17134.137

**Comment by ErickShepherd** [comment]
I apologize for the late response; I only just saw this and never saw an E-mail notification of the issue.

The reason for this issue is because Django template files currently do not have a standard extension (see [this Stack Overflow thread](https://stackoverflow.com/questions/2035362/django-template-file-extension-preference)). Consequently, many Django template files are written with .html filetypes, and this plugin is set to default .html files to Django template syntax highlighting since this mode of highlighting supports all HTML syntax already. Unfortunately, Brackets Live Preview does not support Django templates, thus the error you've encountered.

The way to fix this from the user's end is to change from the plugin-assigned .html default filetype "Django" to the Brackets-native "HTML".

![django to html](https://user-images.githubusercontent.com/24425940/48211307-41261c80-e347-11e8-9e85-95119e61b7b5.png)

I can also fix this on my end with an update to the package if other users can provide me with one or more preferred file extensions for Django templates so that the plugin doesn't have to override the .html file default. (".dj.html", ".djt", etc.)
